
## the index folder for STAR, change to mm9 if it is mouse
STARINDEX: "/home/deepSeq/STAR_index_HS_38.86_small/"

## gtf file for annotation and number of threads used for sorting

MYGTF: "/home/deepSeq/ENSEMBL_GRCH38/transcripts/Homo_sapiens.GRCh38.86.gtf"

SortThreads: "4"

## start from bam or start from fastq
from_fastq: True

## use which program to count 
htseq: True
GroupdFile: False #Groupfile should list the Sample Directories and pheno data in separate columns

## Plots
Plots: True #True to get PCAs,boxplots, and Clusters
BootStraps: 25 #Number of Bootstraps for Hierarchical clustering
ClusterCores: 22 #Number of cores for clustering

# Path to a JSON file with samples and their corresponding FASTQ files.
SAMPLES_JSON: './samples.json'

CLUSTER_JSON: './cluster.json'